# Generated by Django 4.1.7 on 2023-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Description', max_length=255),
        ),
    ]
