# Generated by Django 4.1.7 on 2023-03-14 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qty',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
